### ISSUE TITLE
Поиск датасета с фотороботами

### ISSUE THREAD

**Issue by alxmcs** [alxmcs/CompositePortraitRecongnition#5]
Поскольку тематика завязана на фотороботах, было бы неплохо найти сервис/софт, где их можно создавать. Желательно найти несколько таких, где они генерируются различным образом.
Также гипотетически под задачу подойдут какие-нибудь сервисы по генерации набросков по имеющемуся фото (думаю, что основанных на style-transfer нейронках сервисов сейчас навалом). Более того, если будет желание, можно реализовать такое на [tf](https://www.tensorflow.org/tutorials/generative/style_transfer).

**Comment by alxmcs** [comment]
Предлагаю обратить внимание на  [CUNK student dataset](http://mmlab.ie.cuhk.edu.hk/archive/facesketch.html)
На странице есть еще ссылки на AR dataset и XM2VTS dataset, но ссылки на фотографии к наброскам, похоже, устаревшие, так что вряд ли они пригодятся.

**Comment by alxmcs** [comment]
Мне также удалось получить доступ к [Tufts Face Database](http://tdface.ece.tufts.edu/) (там в отличие от предыдущего датасета, не исключительно азиаты).
В базу есть набор с фотографиями и композитными портретами - TD_CS, ссылка на скачивание [тут](http://tdface.ece.tufts.edu/downloads/TD_CS/).

Источник для ссылок в статьях/тезисах:
` Panetta, Karen, Qianwen Wan, Sos Agaian, Srijith Rajeev, Shreyas Kamath, Rahul Rajendran, Shishir Rao et al. "A comprehensive database for benchmarking imaging systems." IEEE Transactions on Pattern Analysis and Machine Intelligence (2018)`

**Comment by alxmcs** [comment]
Думаю, для диплома этих двух наборов более чем достаточно. Имеем:
* 188 пар (фотография, графический набросок) из CUHK,
* 112 пар (фотография, композитный портрет) из Tufts TD_CS.

_на всякий случай - исследования по каждому набору данных проводить будем отдельно_

@rodinVasiliy, закрой ишью, как утащишь себе на машину оба датасета

**Comment by rodinVasiliy** [comment]
забрал себе оба датасета
